[build]
  base = "frontend"
  publish = "frontend/build"
  command = "CI=false npm run build"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  CI = "false"
  NODE_ENV = "production"
  REACT_APP_API_URL = "https://imageuploader-backend-8uqd.onrender.com/api"
  GENERATE_SOURCEMAP = "false"
